export const sampleJsonResponse = {
  jobs: [
    {
      candidate_required_location: "Worldwide",
      category: "Software Development",
      company_logo: "https://remotive.com/job/1924495/logo",
      company_logo_url: "https://remotive.com/job/1924495/logo",
      company_name: "E-studio",
      description:
        "Salary: $110k-150k annual salary prorated for part-time Who We Are: We're a private equity-backed company passionate about building impactful businesses, particularly in the health and wellness space. We prioritize a positive, collaborative work environment and value kindness, humility, and professionalism. Why Tech? While we're not a tech company, technology plays a vital role in improving our efficiency and supporting our portfolio companies. We're looking for a part-time (3-4 days/week) hands-on tech whiz to join our team. What You'll Do: Coordinate the Design and Development of Our In-House RAG System: You'll be the architect of our in-house Retrieval-Augmented Generation (RAG) system. This will initially involve evaluating/auditing our existing system. It may involve a rebuild, assembling a small team, or outsourcing development. You'll own the overall design and approach, ensuring it directly impacts the success of our portfolio companies. Boost Our Workplace Efficiency: You'll identify opportunities to improve efficiency through digital tools and process automation. Think setting up ETL pipelines, building BI dashboards, and streamlining workflows. Be a Tech Communicator: You'll bridge the gap between technical and non-technical teams. Translating complex concepts into clear language and collaborating with both internal and external stakeholders is key. You Are: A Hands-On Digital Handyman: A seasoned software engineer or architect with a passion for building innovative solutions that solve real-world business problems. A Tech Ninja: You possess a full-stack development skill set, with experience in rapid prototyping, polyglot programming (JavaScript, Python, Go, etc.), and a good understanding of machine learning and data pipelines. Familiarity with RAG systems is a plus! A Communication Powerhouse: You can effectively communicate with everyone, from executives to engineers. You'll translate tech jargon into clear language and represent our company confidently when discussing technical matters. A Collaborative Problem-Solver: You thrive on translating broad goals into actionable plans and can work independently or lead a small team. A Continuous Learner: You're committed to improvement and embrace lean/agile methodologies. A Team Player: You're humble, professional, and enjoy working in a positive, collaborative environment. Intrinsically Motivated: You're driven by creating meaningful impact, not just by a paycheck. Requirements: Bachelor's degree in Software Engineering or a related field. 10+ years of software development experience, with 5+ years in a leadership role (e.g., solutions architect, technical product manager). Technical proficiency in cloud platforms (AWS, Azure, GCP), software architecture, design patterns, security, and performance. Proficiency in TypeScript, Python, and SQL Bonus Points: Experience working at/with startups Experience with any or all of the following: Docker, Kubernetes, NestJS, React, PyTorch, Pandas, Scikit-learn, Google Apps Script Google Workspace administration certifications. Benefits Flexible hours and fully remote USD $110-150K annual salary prorated for part-time, dependent on the candidates qualifications and geographical location Work environment On the days that you are working, you are available for at least 4 hours during the regular work day (Pacific Time Zone) Travel may not be required but participation in some in-person, on-site work activities during the year will be encouraged Application Resume / CV Cover letter (optional) Project portfolio with source code, e.g. GitHub, GitLab, Bitbucket, etc. Join us and be the tech force that helps us and our portfolio companies thrive!",
      id: 1924495,
      job_type: "part_time",
      publication_date: "2024-07-15T22:52:54",
      salary: "$110k-150k",
      tags: [
        "AWS",
        "azure",
        "cloud",
        "docker",
        "fullstack",
        "go",
        "javascript",
        "kubernetes",
        "python",
        "react",
        "security",
        "sql",
        "AI/ML",
        "agile",
        "automation",
        "product management",
        "Typescript ",
        "GCP",
        "ETL",
        "prototyping",
        "gitlab",
        "github",
        "travel",
        "Pytorch",
      ],
      title: "Senior Solutions Architect",
      url: "https://remotive.com/remote-jobs/software-dev/senior-solutions-architect-1924495",
    },
    {
      candidate_required_location: "Sweden",
      category: "Human Resources",
      company_logo: "https://remotive.com/job/1922518/logo",
      company_name: "Intergiro Intl AB (publ)",
      description:
        "Are you interested in joining a rapidly scaling and forward-thinking Swedish FinTech company ? Intergiro is on a mission to connect the digital economy by enabling businesses to embed payments into their systems and products. Our core suite of payment APIs are used by thousands of internet platforms to increase revenue, reduce costs and make their products more sticky. We are a remote team of 100 Intergironauts that work from our hiring locations across Europe (Sweden, Poland, Spain and Portugal). Now we are looking for a People Experience & TA Specialist . Your main goal will be to oversee recruitment and work on various people and culture development tasks across the entire employee journey, while also serving as the point of contact for our employees in people related questions. Our People Ops team (HR and Recruitment) is a small team spread across our main hiring locations, and for this position, we are looking for someone based in Sweden. In this role, you will work closely with our management team and other leaders, and you will also have the support of a senior HR leader in the more traditional HR related matters. This is a great opportunity for someone with recruitment experience who is interested in a broad and varied role, focusing on the total employee journeyfrom employer branding and recruitment to onboarding, creating an engaging culture, and ensuring a positive offboarding experience. We anticipate that your time will be split approximately 50/50 between recruitment and other tasks listed below, although this can vary based on actual recruitment needs. Specifically, your responsibilities will include: Recruitment : Managing the recruitment process through search and advertisement, and collaborating closely with hiring managers across the organisation. Employer Branding : Handling both internal and external communication to ensure that our external image aligns with the internal culture experienced by our employees. Onboarding : Leading the onboarding process for new hires, utilising our HR system, and working with Team Leads to deliver a high-quality introduction to both the company and the specific role. Culture Development Projects : For example organising company meet-ups, conducting workshops with teams (e.g., as part of engagement surveys), contributing to the development of our benefits package, and devising strategies to engage and train remote workers and enhance remote communication. HR System Integration : Integrating our people journey with our HR system, Hibob, and actively participating in its development to support self-service and automation in various aspects of the employee journey, including onboarding, offboarding, managing the benefits portal, conducting company surveys, etc. Employee Communication : Maintaining day-to-day communication with employees and establishing yourself as a visible presence within the organisation as a People Ops representative. While you won't necessarily need to be a specialist in pure HR- or payroll matters, your focus will be on creating a positive employee experience. We take our culture very seriously We want to be the best kind of company and the best kind of environment, for the best kind of people. We aim to offer a workplace where everyone has the space to grow and make an impact on our business. By joining us, youre joining a scale-up with a fun, challenging, open, entrepreneurial culture that will give you responsibilities and a lot of ownership:  We believe in idea meritocracy: the best one wins, no matter where it came from.  We make sure to create a safe space for open communication so everyone can express their views and speak the truth to power.  We continuously seek innovation. We are trying to build something different and better than what is already out there, so we must be the vanguard. Job requirements Proven experience as a tech recruiter, preferably in a fast-paced environment. Experience working with other parts of the employee journey, for example in an HR role or with employer branding, is a plus Strong understanding of recruitment processes, techniques and stakeholder management. Excellent interpersonal and communication skills. Proficiency in applicant tracking systems (ATS) and HRIS software. Strong organisational and time-management skills. Ability to work independently and with strong self-leadership skills A service-minded attitude and a flexible approach to the rapidly changing environment that a scale-up organisation entails Ability to build and maintain effective relationships with candidates and employees Fluent in English and at least basic Swedish skills Its important that you thrive in a remote environment What we offer Opportunity to work with like-minded individuals in a modern, international and fast-paced environment Employment benefits package focused on work/life balance with flexible working hours and the freedom to work fully remote. Pension- & sick leave insurance in line with market levels Wellness allowance A nice co-working office in the central of Stockholm We welcome your application during July and well start to review applicants at the beginning of August.",
      id: 1922518,
      job_type: "full_time",
      publication_date: "2024-07-15T22:50:19",
      salary: "",
      tags: ["onboarding"],
      title: "People Experience- & Talent Acquisition Specialist",
      url: "https://remotive.com/remote-jobs/hr/people-experience-talent-acquisition-specialist-1922518",
    },
    {
      candidate_required_location: "USA",
      category: "Project Management",
      company_logo: "https://remotive.com/job/1923152/logo",
      company_name: "Nomi Health",
      description:
        "We are seeking a passionate Project Manager to join our team! You will manage our day-to-day integrated marketing and production activities. You will successfully manage projects and produce outstanding results, you will play a pivotal role in our mission. Whether you've honed your skills in-house at a global brand or at a leading production house/agency, your expertise in cross-functional collaboration will be invaluable. How you will make an impact Manage the creation and implementation of marketing activities by developing project schedules, managing stakeholders, resourcing, and overall end to end process management (working with internal Nomi Health resources as well as 3rd parties). Uphold a high bar of creative excellence and attention to detail to deliver best in class work. With guidance from the Senior Manager, Marketing Operations, help develop and define efficient production workflows and employ them on day-to-day initiatives. Work seamlessly and manage input and workflows with other stakeholders such as Creative Services, Strategy, Analytics, PR, Legal, etc. Assist in managing any 3rd party vendors and/or production companies. What we are looking for 2-4 years integrated production experience at an agency or in-house. A proven track record of delivering initiatives from conception through completion on time, within budget and on scope; communicating scope creep. Strong familiarity with project management tools and best practices. Strength in creative problem-solving and critical thinking. Shows strong organization and prioritization skills with keen attention to detail. Possesses strong leadership, interpersonal, and teamwork skills. Excels in a fast-pace, innovative environment. Experience with financial and legal management of projects. Knowledge of video and digital production standard methodologies. Knowledge of web, mobile and software technologies. Print/Art buying experience.",
      id: 1923152,
      job_type: "full_time",
      publication_date: "2024-07-15T22:50:14",
      salary: "",
      tags: [
        "video",
        "project management",
        "analytics",
        "marketing operations",
      ],
      title: "Project Manager",
      url: "https://remotive.com/remote-jobs/project-management/project-manager-1923152",
    },
    {
      candidate_required_location: "Egypt",
      category: "Software Development",
      company_logo: "https://remotive.com/job/1923388/logo",
      company_name: "BlackStone eIT",
      description:
        "BlackStone eIT, one of the leading computer software companies, is seeking a highly skilled and experienced Senior SharePoint Developer to join our team. As a Senior SharePoint Developer, you will be responsible for designing, developing, and implementing SharePoint solutions for our clients. You will work closely with our clients, business analysts, and other developers to understand their requirements and deliver top-notch solutions. Responsibilities Designing and developing SharePoint solutions using SharePoint Online and SharePoint Server Collaborating with clients and business analysts to gather and understand requirements Implementing and configuring SharePoint features, applications, workflows, and web parts Creating and maintaining documentation for SharePoint solutions Performing unit testing and supporting quality assurance activities Providing technical support and troubleshooting issues related to SharePoint implementation and customization Staying up to date with the latest developments and best practices in SharePoint development Requirements Bachelor's degree in Computer Science, Software Engineering, or a related field Minimum of 6 years of hands-on experience in SharePoint development Strong proficiency in SharePoint Online, SharePoint Server, and related technologies Experience in gathering requirements and designing SharePoint solutions Extensive experience in developing custom SharePoint features, applications, workflows, and web parts Proficiency in HTML, CSS, JavaScript, and other web technologies Knowledge of SharePoint branding and customization Good understanding of SharePoint administration and configuration Ability to work effectively in a fast-paced, collaborative environment Excellent problem-solving and debugging skills Strong communication and interpersonal skills Experience with SharePoint migration and upgrade projects is a plus Microsoft certifications in SharePoint development or administration is a plus Familiarity with SharePoint Framework (SPFx) is a plus Benefits Paid Time Off Performance Bonus Training & Development",
      id: 1923388,
      job_type: "contract",
      publication_date: "2024-07-15T22:50:09",
      salary: "",
      tags: ["CSS", "html", "javascript"],
      title: "Senior SharePoint Consultant",
      url: "https://remotive.com/remote-jobs/software-dev/senior-sharepoint-consultant-1923388",
    },
    {
      candidate_required_location: "Austria",
      category: "All others",
      company_logo: "https://remotive.com/job/1923601/logo",
      company_name: "Reedsy",
      description:
        "We are seeking experienced book translators to work directly with authors and help them share their stories in a different language. Reedsys vetted group of freelancers help authors through every stage of their publishing journey: from editing to translating to marketing their book. Our professionals have worked on a range of widely acclaimed novels, such as The Hunger Games, Originals (Adam Grant), and His Dark Materials series (Phillip Pullman). Requirements The qualifications we look for are: 3+ years of translating experience. At least 5 translated books that are well-reviewed (and available on Amazon, Apple Books or Google Books) Experience working for a traditional publisher will be positively valued. Though not a requirement, we appreciate it if you are able to copy-edit/proofread your translations (or you work in tandem with a partner who can do it) in order to deliver an error-free translation. Benefits As a translator on Reedsy, you will be able to set your own rates, manage your workload, work where and when you want, collaborate through our intuitive platform, and enjoy Reedsys payment protection. About the company A friendly place for authors to learn, create and market the best indie books We're a community of 1,000,000 authors and freelance publishing professionals. We help authors find top editors, designers and marketers: reedsy.com And we're fully remote!  Read about our co-founder Matt spending 3 months living and working from the Alps: businessinsider.com/i-live-and-work-in-my-car-heres-how-2018-5. And a bit more about how we started here: starterstory.com/book-publishing-services-marketplace.",
      id: 1923601,
      job_type: "freelance",
      publication_date: "2024-07-15T18:51:32",
      salary: "",
      tags: ["editing"],
      title: "Eng-Ger Book Translator",
      url: "https://remotive.com/remote-jobs/all-others/eng-ger-book-translator-1923601",
    },
  ],
};
